name: Merge dev into master

on:
  pull_request:
    branches:
      - dev
    types:
      - closed

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Merge changes
        uses: peter-evans/create-pull-request@v3
        with:
          title: Merge dev into master
          commit-message: Merge pull request #${{ github.event.pull_request.number }} from dev into master
          branch: master
          delete-branch: false
          body: |
            This pull request merges changes from the dev branch into the master branch.
          token: ${{ secrets.TOKEN }}
