name: Merge dev into master

on:
  pull_request:
    branches:
      - dev
    types:
      - closed
      - reopened

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Merge changes into master
        run: |
          git config user.name "Quiirex"
          git config user.email "j6.bountyhounter@gmail.com"
          git checkout master
          git merge --no-ff ${{ github.event.pull_request.head.ref }}
          git push origin master
