name: Merge dev into master

on:
  pull_request:
    branches:
      - dev
    types:
      - closed

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Merge changes
        uses: octokit/request-action@v2.x
        with:
          route: PUT /repos/${{ github.repository }}/merges
          mediaType: '{"previews":["shadow-cat"]}'
          requestBody: |
            {
              "base": "master",
              "head": "dev",
              "commit_message": "Merge dev into master"
            }
          token: ${{ secrets.TOKEN }}
